name: polkawallet_ui
description: Common used Widgets for polkawallet app.
version: 0.5.0
homepage: https://polkawallet.io

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  permission_handler: ^7.2.0
  dropdown_search: ^0.6.3
  url_launcher: ^6.0.4
  intl: ^0.17.0
  qr_flutter_fork: ^4.0.0
  flutter_qr_scan: ^1.0.7
  polkawallet_sdk: ^0.4.9
  webview_flutter: ^3.0.4
  skeleton_loader: ^2.0.0+4
  flutter_screenutil: ^5.0.0+2
  scrollable_positioned_list: ^0.2.3
  card_swiper: ^2.0.3
  share_plus: ^4.0.9
  rive: ^0.9.0
  collection: ^1.16.0
  # simple_shadow: ^0.2.0

dependency_overrides:
 polkawallet_sdk:
   path: ../sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
   - assets/images/
   - assets/fonts/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
